# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "Release" ]
  pull_request:
    branches: [ "Dev" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
       - name: Install Tuist
          run: curl -Ls https://install.tuist.io|bash

        - name: Install Fastlane
          run: brew install fastlane

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Tuist clean
        run: tuist clean

      - name: Tuist fetch
        run: tuist fetch
    
    - name: Build
      run: swift build -v
    - name: Run tests
      run: tuist clean tuist fetch  tuist generate --project-directory=BeatMaster/
        xcodebuild clean test -workspace BeatMaster/BeatMaster.xcworkspace -scheme BeatMaster -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=latest'
