# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "Dev" ]

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v2

      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 15.2.0

    

      # This step was corrected for proper indentation
      - name: Bring ignored files
        uses: actions/checkout@v3
        with:
          key: ${{ secrets.SSH_KEY }}

      - name: Setting Master Key
        uses: actions/checkout@v3
        with:
           key: ${{ secrets.MASTER_KEY }}

      # Corrected indentation for the "Install Tuist" step
      - name: Install Tuist
        run: curl -Ls https://install.tuist.io | bash
        working-directory: ./BeatMaster

      # Corrected indentation for the "Install Fastlane" step
      - name: Install Fastlane
        run: brew install fastlane
        working-directory: ./BeatMaster

      - uses: ruby/setup-ruby@v1
        with:
         ruby-version: '3.3' # Not needed with a .ruby-version file
         bundler-cache: true #

      - name: Tuist clean
        run: tuist clean
        working-directory: ./BeatMaster

      - name: Tuist fetch
        run: tuist fetch
        working-directory: ./BeatMaster


      - name: Tuist Signing Decrypt
        run: tuist signing decrypt
        working-directory: ./BeatMaster

      - name: Tuist Genrate
        run: TUIST_ROOT_DIR=${PWD} tuist generate
        working-directory: ./BeatMaster

      - run: fastlane QA
        env:
          KEYCHAIN_NAME: ${{ secrets.KEYCHAIN_NAME }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
        
