# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "Dev" ]

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v2

      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 15.2.0

   
      # This step was corrected for proper indentation
      - name: Bring ignored files
        uses: actions/checkout@v3
        with:
          key: ${{ secrets.SSH_KEY }}

      - name: Setting Master Key
        run: echo -n "${{ secrets.MASTER_KEY }}" > ./Tuist/master.key
        working-directory: ./BeatMaster
        env:
          MASTER_KEY: ${{ secrets.MASTER_KEY }}

 # uses: actions/checkout@v3
    #     with:
    #        key: ${{ secrets.MASTER_KEY }}

      # Corrected indentation for the "Install Tuist" step
      - name: Install Tuist
        run: curl -Ls https://install.tuist.io | bash
        working-directory: ./BeatMaster

      # Corrected indentation for the "Install Fastlane" step
      - name: Install Fastlane
        run: brew install fastlane
        working-directory: ./BeatMaster

      - uses: ruby/setup-ruby@v1
        with:
         ruby-version: '3.3' # Not needed with a .ruby-version file
         bundler-cache: true #

      - name: Tuist clean
        run: tuist clean
        working-directory: ./BeatMaster

      - name: Tuist fetch
        run: tuist fetch
        working-directory: ./BeatMaster


      - name: Tuist Signing Decrypt
        run: tuist signing decrypt
        working-directory: ./BeatMaster

      # - name: Set Keychain
      #   run: fastlane set_keychain
      #   working-directory: ./BeatMaster
      #   env:
      #     KEYCHAIN_NAME: ${{ secrets.KEYCHAIN_NAME }}
      #     KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}

      - name: Decode and Install Certificate
        run: |
          echo "${{ secrets.IOS_DEVELOPMENT_P12 }}" | base64 --decode > ./Tuist/Signing/release.p12
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security import ./release.p12 -k build.keychain -P ${{ secrets.P12_PASSWORD }} -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain
          security list-keychains -s build.keychain


      - name: Tuist Genrate
        run: TUIST_ROOT_DIR=${PWD} tuist generate
        working-directory: ./BeatMaster

      - run: fastlane QA
        working-directory: ./BeatMaster
        env:
          KEYCHAIN_NAME: ${{ secrets.KEYCHAIN_NAME }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}

      - name: Clean up Keychain
        if: always()
        run: security delete-keychain build.keychain
        
